# A simple bonnie++ setup that spins up 100 instances hitting NFS
# We mostly just wanna see if NFS crashes
apiVersion: batch/v1
kind: Job
metadata:
  name: jupyterhub-benchmark-NUM
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - args:
          - /bin/sh
          - -c
          - "node --trace-warnings stress.js ${HUB_URL} ${COUNT} `hostname` ${STATSD_HOST} ${STATSD_PREFIX}"
        image: yuvipanda/jupyterhub-stress:v0.1
        imagePullPolicy: Always
        name: stress
        env:
          - name: HUB_URL
            value: http://13.88.191.24
          - name: COUNT
            value: RUN_COUNT
          - name: STATSD_PREFIX
            value: jh-perf-01
          - name: STATSD_HOST
            value: 13.64.254.234
