apiVersion: batch/v1
kind: Job
metadata:
  name: jh-load-{{ .Release.Name }}
  labels:
    heritage: {{ .Release.Service }}
    app: jupyterhub-loadtest
    release: {{ .Release.Name }}
spec:
  completions: {{ .Values.completions }}
  parallelism: {{ default .Values.parallelism .Values.completions }}
  backoffLimit: 0
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        app: jupyterhub-loadtest
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - command:
          - node
          - --trace-warnings
          - stress.js
          - --min-user-active-time
          - {{ .Values.users.runTime.min | quote }}
          - --max-user-active-time
          - {{ .Values.users.runTime.max | quote }}
          - --users-start-time
          - {{ .Values.users.startTime.max | quote }}
          - --events-tcp-server
          - $(COLLECTOR_SERVICE_HOST):$(COLLECTOR_SERVICE_PORT)
          - {{ required "hub.url is required" .Values.hub.url | quote }}
          - {{ .Values.users.count | quote }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: stress
